### ISSUE TITLE
Support for NEWS.md

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/maker#33]
Starting with the R devel, `NEWs.md` will be supported by `news()` - see [here](https://stat.ethz.ch/pipermail/bioc-devel/2018-September/014090.html) for details.. We might consider updating or removing the `news` recipe and or document that it might not be required any more.

**Comment by sgibb** [comment]
You are right (the corresponding R/NEWS entry https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2018/08/07#n2018-08-07). I guess it will be part of 3.5.2. I would suggest to just remove the target when it becomes part of the stable R release (hopefully we will remember to do this. (Would be great if github could send reminders; see https://probot.github.io/apps/reminders/ (I already clicked "install" for maker).)

**Comment by lgatto** [comment]
Didn't know about these reminders, nice. Did you set one? Not sure what you mean in *clicked install*.

**Comment by lgatto** [comment]
There's one think though that the target does and that is still useful, which is removing the URL syntax upon conversion from md to plain text. I doubt the links will be displayed properly using `news()` or on the Bioconductor/CRAN pages.

**Comment by sgibb** [comment]
fair point
/remind me to look into this after I updated my R-devel installation tomorrow

**Comment by lgatto** [comment]
Looks great! Yes, it's safe to remove that recipe once that feature is in R release. Or possibly replace it with a note linking to this issue before removing it altogether?

**Comment by sgibb** [comment]
R 3.5.2 isn't released yet.

/remind me to replace the `NEWS` target with a note when R 3.5.2 will have been released in December

**Comment by sgibb** [comment]
R 3.5.2 is announced for the 20. Dec: https://stat.ethz.ch/pipermail/r-announce/2018/000633.html

/remind me to replace the NEWS target with a note when R 3.5.2 will have been released on 21 December

**Comment by sgibb** [comment]
I guess this will be an issue of never ending reminders ...
R 3.5.2 has not any support for NEWS.md. I assume it will be part of R 3.6.0 (maybe mid April 2019)

/remind me to replace the NEWS target with a note when R 3.6.0 will have been released on 20th April
